name: pr
on:
  pull_request:
    braches: 
      - master
      - feat/CK-1933

jobs:
  test:
    runs-on: migrations
    steps:
      - uses: actions/checkout@v2
      # - uses: actions/setup-python@v2
      #   with:
      #     python-version: '3.9'

      # - name: Install dependencies
      #   run: |
      #     pip install -r required
      #     pip install -r require.dev
 
      # - name: run tests
      #   run: |
      #     pytest --cov-report=xml --cov=status-update --cov-report term-missing --cov ${GITHUB_WORKSPACE}/src

      - name: SonarQube Analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: |
          sonar-scanner \
            -Dsonar.sources=. \
            -Dsonar.host.url=${SONAR_HOST_URL} \
            -Dsonar.login=${SONAR_TOKEN}
